#!/usr/bin/env python

'''
Created by Samvel Khalatyan, Feb 09, 2012
Copyright 2011, All rights reserved

Plot templates generated by Hadronic Top analyzer
'''

from __future__ import print_function

import sys

import root.style

from hadronic_top.template import HadronicTopTemplates as Templates

def usage(argv):
    return "usage: {0[0]} input.root".format(argv)

def main(argv = sys.argv):
    '''
    application entry point

    run executable without arguments to see usage
    '''
    
    try:
        if 2 > len(argv):
            raise Exception("input is not specified")

        root.style.tdr()

        templates = Templates()
        templates.use_folders = ["jet1", "top" ]
        templates.ban_plots = [ "px", "py", "pz", "phi" ]

        templates.load(argv[1])

        if not templates:
            raise Exception("failed to laod templates")

        canvases = templates.draw()
        raw_input("enter")

    except Exception as error:
        print(error, file = sys.stderr)
        print()
        print(usage(argv))

        return 0
    else:
        return 1

if "__main__" == __name__:
    sys.exit(main())
