// Read input file generated by cutflow.sh and apply scales
//
// Created by Samvel Khalatyan, Dec 14, 2011
// Copyright 2011, All rights reserved

#include <iostream>

#include "interface/Cutflow.h"

using namespace std;

int main(int argc, char *argv[])
{
    if (2 > argc)
    {
        cerr << "Usage: " << argv[0] << " cutflow.txt" << endl;

        return 0;
    }

    Cutflow cutflow;
    cutflow.load(argv[1]);

    return 0;
}
